In [60]:
import numpy as np

x = np.arange(10)

# Native arithmentic operators
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 5 =", x * 5)
print("x / 5 =", x / 5)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

# OR we can use explicit functions, ufuncs, e.g. "add" instead of "+"
print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.multiply(x, 5))
print(np.divide(x, 5))
print(np.power(x, 2))
print(np.mod(x, 2))

x = [0 1 2 3 4 5 6 7 8 9]
x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 5 = [ 0  5 10 15 20 25 30 35 40 45]
x / 5 = [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
x ** 2 =  [ 0  1  4  9 16 25 36 49 64 81]
x % 2  =  [0 1 0 1 0 1 0 1 0 1]
[ 5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  5 10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [62]:
theta = np.linspace(0, np.pi, 4)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.04719755 2.0943951  3.14159265]
sin(theta) =  [0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]
cos(theta) =  [ 1.   0.5 -0.5 -1. ]
tan(theta) =  [ 0.00000000e+00  1.73205081e+00 -1.73205081e+00 -1.22464680e-16]


In [63]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
ln(x)    = [0.         0.69314718 1.09861229]
log2(x)  = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


In [64]:
x = np.arange(1, 6)
sum_all = np.add.reduce(x)

print(x)
print(sum_all)

[1 2 3 4 5]
15


In [65]:
x = np.arange(1, 6)
sum_acc = np.add.accumulate(x)

print(x)
print(sum_acc)

[1 2 3 4 5]
[ 1  3  6 10 15]


In [66]:
import numpy as np

x = np.random.random(100)

# Sum of all the values
print("Sum of values is:", np.sum(x))
# Mean value
print("Mean value is: ", np.mean(x))

#For min, max, sum, and several other NumPy aggregates, 
#a shorter syntax is to use methods of the array object itself,
# i.e. instead of np.sum(x), we can use x.sum()
print("Sum of values is:", x.sum())
print("Mean value is: ", x.mean())
print("Max value is: ", x.max())
print("Min value is: ", x.min())

Sum of values is: 51.772664531956345
Mean value is:  0.5177266453195635
Sum of values is: 51.772664531956345
Mean value is:  0.5177266453195635
Max value is:  0.9967564913221365
Min value is:  0.0003984950783277874


In [68]:
import numpy as np

grid = np.random.random((3, 4))
print(grid)

print("Overall sum:", grid.sum())
print("Overall Min:", grid.min())

# Row wise and column wise min
print("Column wise minimum: ", np.amin(grid, axis=0))
print("Row wise minimum: ", np.amin(grid, axis=1))

[[0.45569629 0.0866532  0.28288488 0.75284814]
 [0.53751804 0.31860711 0.87452861 0.96604197]
 [0.55756503 0.86344049 0.89440579 0.00855409]]
Overall sum: 6.598743651456712
Overall Min: 0.008554094776975552
Column wise minimum:  [0.45569629 0.0866532  0.28288488 0.00855409]
Row wise minimum:  [0.0866532  0.31860711 0.00855409]


In [69]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

print(x < 2) # less than
print(x >= 4) # greater than or equal

[ True False False False False]
[False False False  True  True]


In [70]:
x = np.array([1, 2, 3, 4, 5])

# Elements for which multiplying by two is the same as the square of the value
(2 * x) == (x ** 2)
#> array([False,  True, False, False, False], dtype=bool)

array([False,  True, False, False, False])

In [79]:

x = np.arange(10)
print(x)

# How many values less than 6?
print(np.count_nonzero(x < 6))

# Are there any values greater than 8?
print(np.any(x > 8))

# Are all values less than 10?
print(np.all(x < 10))

[0 1 2 3 4 5 6 7 8 9]
6
True
True


In [80]:
import numpy as np 

# Random integers between [0, 10) of shape 3x3
x = np.random.randint(0, 10, (3, 3))
print(x)

# Boolean array
print(x < 6)

# Boolean mask
print(x[x < 6])


[[8 2 4]
 [3 4 0]
 [2 7 2]]
[[False  True  True]
 [ True  True  True]
 [ True False  True]]
[2 4 3 4 0 2 2]


[[6 5 1]
 [8 6 0]
 [5 0 6]]
[5 1 0 5 0]
