In [19]:
import numpy as np
Z=np.zeros(10);
print(Z)

import numpy as np
arr=np.arange(10)
print(arr)

arr=np.random.random([3,3,3]) 
print(arr)

arr=np.random.random([10,10])
min_val=arr.min()
max_val=arr.max()
print(min_val)
print(max_val)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 2 3 4 5 6 7 8 9]
[[[0.1548526  0.80055347 0.93535871]
  [0.85410976 0.96575173 0.385155  ]
  [0.14962149 0.09604674 0.9919374 ]]

 [[0.53929397 0.20651785 0.0059228 ]
  [0.97308913 0.44758748 0.49833004]
  [0.05215259 0.21776266 0.29177818]]

 [[0.53015585 0.05200467 0.64362413]
  [0.03493434 0.54431301 0.44527886]
  [0.15036903 0.66389286 0.87285606]]]
0.004330685324697048
0.995726976541151


In [30]:
import numpy as np
grid=np.arange(1,10).reshape([3, 3])
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
arr6 = np.arange(10)
arr6[arr6.argmax()]=-1
print(arr6)


[ 0  1  2  3  4  5  6  7  8 -1]


In [55]:
arr7 = np.arange(9).reshape(3,3)
arr7 = arr7[::1,::-1]